# deploy-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-deployer-binding
subjects:
  - kind: User
    name: github-actions      # Must match the 'username' in aws-auth ConfigMap
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: github-actions-deployer   # Must match the ClusterRole name
  apiGroup: rbac.authorization.k8s.io