# k8s-manifests/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-eks-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-eks-demo
  template:
    metadata:
      labels:
        app: node-eks-demo
    spec:
      containers:
        - name: node-eks-demo
          image: 891612562954.dkr.ecr.us-east-1.amazonaws.com/bullion/server:latest # Update the image tag
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName